### ISSUE TITLE
Would be nice to avoid the `-repo.tar.gz` archive

### ISSUE THREAD

**Issue by lapo-luchini** [polo-language/cassandra3#1]
I'm not sure there's a nice way to both make Poudriere happy by fetching dependencies during `fetch` phase instead of `compile`, but avoiding the extra external repository would be nice.
PS: I'm trying to upgrade to 3.11.3, but first I have to produce the updated repo.

**Comment by polo-language** [comment]
Generating and packaging the repo for Maven builds is for now the standard (see for example the ports java/eclipse, archivers/snappy-java).

See this message thread discussing a potential path to resolving this inconvenience:
https://lists.freebsd.org/pipermail/freebsd-ports/2016-June/103442.html
This would be a significant independent undertaking of its own.

I will take care of the 3.11.3 upgrade.
