### ISSUE TITLE
[RFE?][patch] Use `daemon` to auto-restart

### ISSUE THREAD

**Issue by lapo-luchini** [polo-language/cassandra3#3]
Maybe it's just me, as I have a couple of nodes which are a little memory challenged and at times die in `OutOfMemory` errors… but seems a nice idea to auto-restart Cassandra if/when it dies anyways, and the overhead is almost none. What do you think of it?

```diff
% diff -u cassandra-rc.orig /usr/local/etc/rc.d/cassandra | ydiff
--- cassandra-rc.orig   2021-01-08 16:31:54.882744000 +0100
+++ /usr/local/etc/rc.d/cassandra       2021-01-08 16:53:04.255109000 +0100
@@ -25,12 +25,11 @@
 : ${cassandra_enable:=NO}
 : ${cassandra_user:=cassandra}

-command=/usr/local/bin/cassandra
+pidfile=/var/run/cassandra/cassandra.pid
-command_args="-p /var/run/cassandra/cassandra.pid >/dev/null 2>/dev/null"
+
+command=/usr/sbin/daemon
+command_args="-frP ${pidfile} /usr/local/bin/cassandra -f"
 start_precmd="${name}_prestart"
-
-procname=/usr/local/openjdk8/bin/java
-pidfile=/var/run/cassandra/cassandra.pid

 cassandra_prestart()
 {

```

**Comment by polo-language** [comment]
Seems reasonable to me. Why don't you create a FreeBSD bug report with the patch, we'll see if anyone else wants to weigh in.

**Comment by lapo-luchini** [comment]
Makes sense.
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=252610

**Comment by polo-language** [comment]
This was committed in r565154. Thanks for the patch!
