### ISSUE TITLE
Python3 support for `COPY`

### ISSUE THREAD

**Issue by lapo-luchini** [polo-language/cassandra3#4]
Hi! Your (wonderful!) back-port of Python3 support for Cassandra3's `cqlsh` might have a slight bug (which I'm still investigatinv better but Ill write here to remember in the meanwhile):

```
cqlsh:dbname> COPY tablename (fieldname) TO 'file.csv';
Using 7 child processes
name 'long' is not defined
```

**Comment by lapo-luchini** [comment]
This is [due to this](https://github.com/polo-language/cassandra/blame/python3-for-3.11/pylib/cqlshlib/copyutil.py#L544) (and a few others) as [Python3 renamed long to int](https://stackoverflow.com/a/14904834/166524):
`self.max_output_size = long(options.copy['maxoutputsize'])`
which should become
`self.max_output_size = int(options.copy['maxoutputsize'])`

**Comment by lapo-luchini** [comment]
In Cassandra4 (branch trunk) that line seems to have been fixed in commit https://github.com/polo-language/cassandra/commit/bf9a1d487b9ba469e8d740cf7d1cd419535a7e79.

**Comment by polo-language** [comment]
Thanks for researching this. I'll take a look at the upstream patch.

**Comment by lapo-luchini** [comment]
Hi! Any news? 😇

**Comment by polo-language** [comment]
Let this one slip for a little while. At this point updating to 3.11.11 is probably safer and should come with other benefits as well.

**Comment by polo-language** [comment]
This is turning out to be difficult... ccm errors out while trying to initialize for the tests. Incidentally ccm only claims support up to python3.6. Running `make clean test` ends up with:

> \+ ccm start --wait-for-binary-proto --root
> // ...
> 15:13:48,151 ccm DEBUG C* process with 30956 is terminated
> C* process with 30956 is terminated
> Standard error output is:
> Traceback (most recent call last):
>   File "/usr/ports/databases/cassandra3/work/apache-cassandra-3.11.11-src/venv/src/ccm/ccmlib/cmds/cluster_cmds.py", line 518, in run
>     allow_root=self.options.allow_root) is None:
>   File "/usr/ports/databases/cassandra3/work/apache-cassandra-3.11.11-src/venv/src/ccm/ccmlib/cluster.py", line 549, in start
>     error_on_pid_terminated=True)
>   File "/usr/ports/databases/cassandra3/work/apache-cassandra-3.11.11-src/venv/src/ccm/ccmlib/node.py", line 586, in watch_log_for
>     self.raise_node_error_if_cassandra_process_is_terminated()
>   File "/usr/ports/databases/cassandra3/work/apache-cassandra-3.11.11-src/venv/src/ccm/ccmlib/node.py", line 670, in raise_node_error_if_cassandra_process_is_terminated
>     raise NodeError(msg)
> ccmlib.node.NodeError: C* process with 30956 is terminated
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/ports/databases/cassandra3/work/apache-cassandra-3.11.11-src/venv/bin/ccm", line 7, in <module>
>     exec(compile(f.read(), __file__, 'exec'))
>   File "/usr/ports/databases/cassandra3/work/apache-cassandra-3.11.11-src/venv/src/ccm/ccm", line 112, in <module>
>     cmd.run()
>   File "/usr/ports/databases/cassandra3/work/apache-cassandra-3.11.11-src/venv/src/ccm/ccmlib/cmds/cluster_cmds.py", line 527, in run
>     for line in e.process.stderr_file.readlines():
> AttributeError: 'NoneType' object has no attribute 'stderr_file'
> *** Error code 1
> 
> Stop.
> make: stopped in /usr/ports/databases/cassandra3

**Comment by polo-language** [comment]
Updated to 3.11.11 and CQLSH COPY now supported! Thank you for your patience.

Upgrade ticket submitted to FreeBSD bugs:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=261220
