### ISSUE TITLE
Upgrade to 3.11.14

### ISSUE THREAD

**Issue by lapo-luchini** [polo-language/cassandra3#5]
Please. 😇

I'd do it myself, but I'm not sure how to create the tarball… if you have pointers on that, I can try and provide a PR.

**Comment by polo-language** [comment]
I'll start on this soon. Thanks for the reminder.

**Comment by lapo-luchini** [comment]
Yay for e084613a39f408f47c7487482c59799109756d02. =)

**Comment by polo-language** [comment]
Thanks for the encouragement. Submitted bug [267624](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=267624).

**Comment by polo-language** [comment]
Download the [maven repo](https://drive.google.com/file/d/1q05NS2qLsD58CzN6QMaZ0-TOEp3tSHxL) to /usr/ports/distfiles if you would like to use 3.11.14 before it gets committed to the ports tree.
